In [1]:
import numpy as np

# Array Manipulation Routines
These routines are broadly classified as:
1. Changing Array Shapes
2. Changing kind of arrays
3. Splitting Arrays
4. Inserting and Deleting Elements

# 1. Changing Array Shapes
Arrays shape can be changed using numpy.reshape and ndarray.flatten functions

# numpy.reshape
Gives a new shape to an array without changing its data.
1. Syntax: numpy.reshape(a, newshape, order='C')

In [4]:
a=np.array([i for i in range(0,25)])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [3]:
a=np.reshape(a,(5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Flatten
Return a copy of the array collapsed into one dimension.
1. ndarray.flatten(order='C')

In [5]:
a = np.array([[1,2], [3,4]])
a.flatten()


array([1, 2, 3, 4])

# 2- Changing Kind of Array

# numpy.asarray
Convert the input to an array
1. Syntax: numpy.asarray(a, dtype=None, order=None, like=None)

In [9]:
a = [1, 2]
print(type(a))
a=np.asarray(a)
print(type(a))


<class 'list'>
<class 'numpy.ndarray'>


# numpy.asmatrix
Interpret the input as a matrix.
1. Syntax:numpy.asmatrix(data, dtype=None)

In [10]:
x = np.array([[1, 2], [3, 4]])
print(type(x))
m = np.asmatrix(x)
print(type(m))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


# numpy.asfarray
Return an array converted to a float type
1. Syntax: numpy.asfarray(a)

In [13]:
a=np.asfarray([2, 3])
print(a)
print(a.dtype)

[2. 3.]
float64


# numpy.asscalar
Convert an array of size 1 to its scalar equivalent.
1. Syntax:- numpy.asscalar(a)

In [16]:
np.asscalar(np.array([24]))

C:\Users\jasme\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  """Entry point for launching an IPython kernel.


24

# 3. Splitting Arrays
It can split arrays into sub arrays either horizontally or vertically

# numpy.split
Split an array into multiple sub-arrays as views into ary
1. Syntax:-numpy.split(ary, indices_or_sections, axis=0)
2. indices_or_sections: int or 1-D array.
If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis.
If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split. For example, [2, 3] would, for axis=0, result in ary[:2] ary[2:3] ary[3:]


In [25]:
x = np.arange(9.0)
b=np.split(x, 3)
c=np.split(x, [3, 5, 6, 10])
print(b)
print(c)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]
[array([0., 1., 2.]), array([3., 4.]), array([5.]), array([6., 7., 8.]), array([], dtype=float64)]


# numpy.hsplit 
Split an array into multiple sub-arrays horizontally (column wise)
1. Syntax:-numpy.hsplit(ary, indices_or_sections)


In [26]:
x = np.arange(16.0).reshape(4, 4)
b=np.hsplit(x, 2)
c=np.hsplit(x, np.array([3, 6]))
print(b)
print(c)

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]
[array([[ 0.,  1.,  2.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.],
       [12., 13., 14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]]), array([], shape=(4, 0), dtype=float64)]


# numpy.vsplit
Split an array into multiple sub-arrays vertically (row-wise)
1. Syntax:- numpy.vsplit(ary, indices_or_sections)

In [28]:
x = np.arange(16.0).reshape(4, 4)
print(x)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [29]:
b=np.vsplit(x, 2)
c=np.vsplit(x, np.array([3, 6]))
print(b)
print(c)

[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), array([], shape=(0, 4), dtype=float64)]


# 4. Inserting and Deleting Elements

# numpy.delete
Return a new array with sub-arrays along an axis deleted.
1. Syntax:-numpy.delete(arr, obj, axis=None)


In [32]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
np.delete(arr, 0, 0)


array([[5, 6, 7, 8]])

# numpy.insert
Insert values along the given axis before the given indices.
1. Syntax:- numpy.insert(arr, obj, values, axis=None)

In [34]:
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, 1, 5,axis=1)


array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [36]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

# numpy.append
Append values to the end of an array.
1. Syntax: numpy.append(arr, values, axis=None)

In [37]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# numpy.resize
Return a new array with the specified shape.
1. Syntax:- numpy.resize(a, new_shape)


In [42]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

# numpy.unique
Find the unique elements of an array.
1. Syntax:- numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)


In [44]:
np.unique([1, 1, 2, 2, 3, 3], return_counts=True,return_index=True, return_inverse=True)


(array([1, 2, 3]),
 array([0, 2, 4], dtype=int32),
 array([0, 0, 1, 1, 2, 2], dtype=int32),
 array([2, 2, 2]))

# Searching, Sorting, and Counting Routines

# numpy.sort
Return a sorted copy of an array
1. Syntax:- numpy.sort(a, axis=- 1, kind=None, order=None)

In [45]:
a = np.array([[4,1],[3,1]])
np.sort(a)


array([[1, 4],
       [1, 3]])

# numpy.argsort
Returns the indices that would sort an array
1. Syntax:- numpy.argsort(a, axis=- 1, kind=None, order=None)

In [46]:
a = np.array([[4,1],[3,1]])
np.argsort(a)


array([[1, 0],
       [1, 0]], dtype=int32)

# numpy.partition
Return a partitioned copy of an array
1. Syntax:- numpy.partition(a, kth, axis=- 1, kind='introselect', order=None)

In [47]:
a = np.array([3, 4, 2, 1])
np.partition(a, 3)


array([2, 1, 3, 4])

# numpy.argmax
Returns the indices of the maximum values along an axis
1. Syntax:- numpy.argmax(a, axis=None, out=None)


In [56]:
a = np.arange(6).reshape(2,3) + 10
print(a)
np.argmax(a)


[[10 11 12]
 [13 14 15]]


5

In [57]:
a = np.arange(6).reshape(2,3) + 10
print(a)
np.argmax(a,axis=0)


[[10 11 12]
 [13 14 15]]


array([1, 1, 1], dtype=int32)

# numpy.nanargmax
Return the indices of the maximum values in the specified axis ignoring NaNs.
1. Syntax:- numpy.nanargmax(a, axis=None)


In [58]:
a = np.array([[np.nan, 4], [2, 3]])
np.nanargmax(a)


1

In [59]:
a = np.array([[np.nan, 4], [2, 3]])
np.nanargmax(a,axis=1)


array([1, 1], dtype=int32)

# numpy.argmin
Returns the indices of the minimum values along an axis
1. Syntax:- numpy.argmin(a, axis=None, out=None) 

In [60]:
a = np.arange(6).reshape(2,3) + 10
np.argmin(a)


0

# numpy.nanargmin
Return the indices of the minimum values in the specified axis ignoring NaNs
1. Syntax:- numpy.nanargmin(a, axis=None)

In [63]:
a = np.array([[np.nan, 4], [2, 3]])
np.nanargmin(a)

2

# numpy.nonzero
Return the indices of the elements that are non-zero.
1. Syntax:- numpy.nonzero(a)

In [65]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
np.nonzero(x)

[[3 0 0]
 [0 4 0]
 [5 6 0]]


(array([0, 1, 2, 2], dtype=int32), array([0, 1, 0, 1], dtype=int32))

# numpy.flatnonzero
Return indices that are non-zero in the flattened version of a
1. Syntax:- numpy.flatnonzero(a)

In [66]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
np.flatnonzero(x)

[[3 0 0]
 [0 4 0]
 [5 6 0]]


array([0, 4, 6, 7], dtype=int32)

# Linear Algebra Routines
Various Linear Algebra Functions are divided into following categories:
1. Matrix and Vector Products
2. Decomposition
3. Eigen Values and Eigen Vectors
4. Norm and Other Numbers
5. Solving Equations and inverting matrices

# 1. Matrix and Vector Products


# numpy.dot
Dot product of two arrays
 1. Syntax:- numpy.dot(a, b, out=None)

In [67]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)


array([[4, 1],
       [2, 2]])

# numpy.inner
Compute the inner product of two vectors
1. Syntax:- numpy.inner(a, b, out=None)

In [68]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.inner(a, b)

array([[4, 2],
       [1, 2]])

# numpy.outer
Compute the outer product of two vectors
1. Syntax:- numpy.outer(a, b, out=None)


In [69]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.outer(a, b)


array([[4, 1, 2, 2],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [4, 1, 2, 2]])

# numpy.matmul
Matrix product of two arrays
1. Syntax:-numpy.matmul(x1, x2, out=None, casting='same_kind', order='K', dtype=None)

In [70]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

# linalg.matrix_power
Raise a square matrix to the (integer) power n
1. Syntax:- linalg.matrix_power(a, n)


In [73]:
a = [[4, 0], [0, 3]]
np.linalg.matrix_power(a,2)

array([[16,  0],
       [ 0,  9]])

# 2. Decomposition 
contains routines for SVD decomposition


# linalg.svd
Singular Value Decomposition
1. Syntax:- linalg.svd(a, full_matrices=True, compute_uv=True)

In [74]:
b = [[4, 1], [2, 2]]
u,s,v=np.linalg.svd(b)


In [75]:
u

array([[-0.83975136, -0.54297114],
       [-0.54297114,  0.83975136]])

In [76]:
s

array([4.8441569 , 1.23860563])

In [77]:
v

array([[-0.91758954, -0.39752916],
       [-0.39752916,  0.91758954]])

# 3. EIGEN VALUES & VECTORS


# linalg.eig
Compute the eigenvalues and right eigenvectors of a square array
1. Syntax:- linalg.eig(a)


In [78]:
b = [[4, 1], [2, 2]]
value,vector=np.linalg.eig(b)


In [80]:
value

array([4.73205081, 1.26794919])

In [81]:
vector

array([[ 0.80689822, -0.34372377],
       [ 0.59069049,  0.9390708 ]])

# numpy.eigvals
Compute the eigenvalues of a general matrix
1. Syntax:- linalg.eigvals(a)

In [79]:
b = [[4, 1], [2, 2]]
value=np.linalg.eigvals(b)

In [82]:
value

array([4.73205081, 1.26794919])

# 4. Norm and Other Numbers


# numpy.norm
Matrix or vector norm
1. Syntax:-linalg.norm(x, ord=None, axis=None, keepdims=False)


In [83]:
b = [[4, 1], [2, 2]]
value=np.linalg.norm(b)

In [84]:
value

5.0

In [85]:
b = [[4, 1], [2, 2]]
value=np.linalg.norm(b,axis=0)

In [86]:
value

array([4.47213595, 2.23606798])

In [87]:
b = [[4, 1], [2, 2]]
value=np.linalg.norm(b,axis=1)

In [88]:
value

array([4.12310563, 2.82842712])

# numpy.det
Compute the determinant of an array
1. Syntax:- linalg.det(a)

In [90]:
b = [[4, 1], [2, 2]]
np.linalg.det(b)

6.0

# numpy.rank
Return matrix rank of array using SVD method
1. Syntax:- linalg.matrix_rank(M, tol=None)


In [91]:
b = [[4, 1], [2, 2]]
value=np.linalg.matrix_rank(b)
value

2

# 5. SOLVING EQUATIONS AND INVERTING MATRICES


# linalg.solve
Solve a linear matrix equation, or system of linear scalar equations.
1. Syntax:- linalg.solve(a, b)

In [92]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)

In [93]:
x

array([-1.,  1.])

# linalg.lstsq
Return the least-squares solution to a linear matrix equation.
1. Syntax:- linalg.lstsq(a, b)

In [94]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.lstsq(a, b)

C:\Users\jasme\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


In [95]:
x

(array([-1.,  1.]),
 array([], dtype=float64),
 2,
 array([6.24294338, 0.16018085]))

# linalg.inv
Compute the (multiplicative) inverse of a matrix
1. Syntax:- linalg.inv(a)


In [96]:
a = np.array([[1, 2], [3, 5]])
x = np.linalg.inv(a)

In [97]:
x

array([[-5.,  2.],
       [ 3., -1.]])

# Statistics Routines

# Average and Variances

# numpy.median
Compute the median along the specified axis
1. Syntax::-numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

In [98]:
a = np.array([[1, 2], [3, 5]])
np.median(a)

2.5

In [101]:
a = np.array([[1, 2], [3, 5]])
np.median(a,axis=0)

array([2. , 3.5])

# numpy.average
Compute the weighted average along the specified axis
Syntax:- numpy.average(a, axis=None, weights=None, returned=False)

In [102]:
np.average(np.arange(1, 11), weights=np.arange(10, 0, -1))

4.0

# numpy.mean
Compute the arithmetic mean along the specified axis
1. Syntax:- numpy.mean(a, axis=None, dtype=None, out=None)

In [103]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

# numpy.std
Compute the standard deviation along the specified axis
1. Syntax:- numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)

In [104]:
a = np.array([[1, 2], [3, 5]])
np.std(a)

1.479019945774904

# numpy.var
Compute the variance along the specified axis
1. Syntax:- numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)

In [105]:
a = np.array([[1, 2], [3, 5]])
np.var(a)

2.1875

# numpy.corrcoef
Return Pearson product-moment correlation coefficients.
1. Syntax:- numpy.corrcoef(x, y=None, rowvar=True, dtype=None)

In [109]:
a = np.array([[1, 2], [3, 5]])
a = np.array([[1, 2], [3, 4]])

np.corrcoef(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# numpy.cov
Estimate a covariance matrix, given data and weights.
1. Syntax:- numpy.cov(m, y=None, rowvar=True, bias=False, ddof=None)


In [110]:
a = np.array([[1, 2], [3, 5]])
np.cov(a)

array([[0.5, 1. ],
       [1. , 2. ]])

# numpy.percentile
Compute the q-th percentile of the data along the specified axis
1. Syntax:- numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)

In [111]:
a = np.array([[10, 7, 4], [3, 2, 1]])
np.percentile(a, 50)

3.5

# numpy.quantile
Compute the q-th quantile of the data along the specified axis
1. Syntax:- numpy.quantile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)

In [112]:
a = np.array([[10, 7, 4], [3, 2, 1]])
np.percentile(a, 0.5)

1.025